package hu.schutz.curlycircleandroidapp.ui.theme

import androidx.compose.ui.graphics.Color

// Generated with Material Theme builder: https://m3.material.io/theme-builder#/custom

val md_theme_light_primary = Color(0xFF1B6D24)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA3F69C)
val md_theme_light_onPrimaryContainer = Color(0xFF002204)
val md_theme_light_secondary = Color(0xFF6349BF)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE7DEFF)
val md_theme_light_onSecondaryContainer = Color(0xFF1E0060)
val md_theme_light_tertiary = Color(0xFF266C21)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFA9F598)
val md_theme_light_onTertiaryContainer = Color(0xFF002201)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF6FEFF)
val md_theme_light_onBackground = Color(0xFF001F24)
val md_theme_light_surface = Color(0xFFF6FEFF)
val md_theme_light_onSurface = Color(0xFF001F24)
val md_theme_light_surfaceVariant = Color(0xFFDEE5D8)
val md_theme_light_onSurfaceVariant = Color(0xFF424940)
val md_theme_light_outline = Color(0xFF72796F)
val md_theme_light_inverseOnSurface = Color(0xFFD0F8FF)
val md_theme_light_inverseSurface = Color(0xFF00363D)
val md_theme_light_inversePrimary = Color(0xFF88D982)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF1B6D24)
val md_theme_light_outlineVariant = Color(0xFFC2C9BD)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF88D982)
val md_theme_dark_onPrimary = Color(0xFF003909)
val md_theme_dark_primaryContainer = Color(0xFF005312)
val md_theme_dark_onPrimaryContainer = Color(0xFFA3F69C)
val md_theme_dark_secondary = Color(0xFFCCBEFF)
val md_theme_dark_onSecondary = Color(0xFF340C90)
val md_theme_dark_secondaryContainer = Color(0xFF4B2EA6)
val md_theme_dark_onSecondaryContainer = Color(0xFFE7DEFF)
val md_theme_dark_tertiary = Color(0xFF8ED97F)
val md_theme_dark_onTertiary = Color(0xFF003A03)
val md_theme_dark_tertiaryContainer = Color(0xFF055308)
val md_theme_dark_onTertiaryContainer = Color(0xFFA9F598)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F24)
val md_theme_dark_onBackground = Color(0xFF97F0FF)
val md_theme_dark_surface = Color(0xFF001F24)
val md_theme_dark_onSurface = Color(0xFF97F0FF)
val md_theme_dark_surfaceVariant = Color(0xFF424940)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C9BD)
val md_theme_dark_outline = Color(0xFF8C9388)
val md_theme_dark_inverseOnSurface = Color(0xFF001F24)
val md_theme_dark_inverseSurface = Color(0xFF97F0FF)
val md_theme_dark_inversePrimary = Color(0xFF1B6D24)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF88D982)
val md_theme_dark_outlineVariant = Color(0xFF424940)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF2E7D32)